# Generated by Django 2.2.15 on 2020-08-26 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('telefonoNumero', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('idEstadoUsuario', models.CharField(blank=True, choices=[('Pendiente', 'Pendiente de activación'), ('Activo', 'Activo'), ('Suspendido', 'Suspendido'), ('Eliminado', 'Eliminado')], default='Pendiente', max_length=60, null=True)),
                ('idTipoUsuario', models.CharField(blank=True, choices=[('Administrador', 'Administrador'), ('Visitante', 'Visitante')], default='Visitante', max_length=60, null=True)),
                ('activacion_token', models.CharField(blank=True, max_length=40, null=True)),
                ('olvido_token', models.CharField(blank=True, max_length=40, null=True)),
                ('fechaBaja', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
