# Generated by Django 3.1 on 2020-09-19 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20200905_1759'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sitio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('motivo_baja', models.CharField(blank=True, max_length=200, null=True)),
                ('publicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sitio.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuarioDenunciado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=1000)),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('fecha_baja', models.DateTimeField(null=True)),
                ('motivo_baja', models.CharField(max_length=200)),
                ('estado_comentario', models.CharField(blank=True, choices=[('Publicado', 'Publicado'), ('Borrador', 'Borrador'), ('Denunciado', 'Denunciado'), ('Eliminado', 'Eliminado')], max_length=10)),
                ('publicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sitio.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
