# Generated by Django 2.2.16 on 2020-09-28 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sitio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuarioReceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_receive', to=settings.AUTH_USER_MODEL)),
                ('idUsuarioSolicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_create', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
