# Generated by Django 3.1 on 2020-09-28 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0002_comentario_denuncia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='usuarioDenunciado',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Denuncia',
        ),
    ]
