# Generated by Django 3.1 on 2020-09-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0003_auto_20200928_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(choices=[('Matemáticas', 'Matemáticas'), ('Sociales', 'Sociales'), ('Naturales', 'Naturales'), ('Lengua', 'Lengua'), ('InglesI', 'InglesI'), ('InglesII', 'InglesII'), ('InglesIII', 'InglesIII'), ('Literatura', 'Literatura'), ('Historia', 'Historia'), ('Química', 'Química'), ('Informática', 'Informática')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='estadoPublicacion',
            field=models.CharField(blank=True, choices=[('Publicado', 'Publicado'), ('Borrador', 'Borrador')], max_length=50, null=True),
        ),
    ]
