# Generated by Django 3.1 on 2020-09-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0004_auto_20200928_2255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Materia',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='materia',
            field=models.CharField(choices=[('Matemáticas', 'Matemáticas'), ('Sociales', 'Sociales'), ('Naturales', 'Naturales'), ('Lengua', 'Lengua'), ('InglesI', 'InglesI'), ('InglesII', 'InglesII'), ('InglesIII', 'InglesIII'), ('Literatura', 'Literatura'), ('Historia', 'Historia'), ('Química', 'Química'), ('Informática', 'Informática')], max_length=50, null=True),
        ),
    ]
