# Generated by Django 3.1 on 2020-10-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0004_denuncia'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='estadoDenuncia',
            field=models.CharField(blank=True, choices=[('Denunciado', 'Denunciado'), ('Eliminado', 'Eliminado')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='estadoPublicacion',
            field=models.CharField(blank=True, choices=[('Publicado', 'Publicado'), ('Borrador', 'Borrador'), ('Eliminado', 'Eliminado'), ('Denunciado', 'Denunciado')], max_length=50, null=True),
        ),
    ]
