# Generated by Django 3.1 on 2020-09-28 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0005_auto_20200928_2300'),
        ('Sitio', '0002_solicitudcontacto'),
    ]

    operations = [
    ]
