# Generated by Django 3.1 on 2020-10-15 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sitio', '0005_auto_20201014_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='fechaBajaComentario',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='fechaComentario',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='motivoBaja',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='estadoComentario',
            field=models.CharField(blank=True, choices=[('Publicado', 'Publicado'), ('Denunciado', 'Denunciado'), ('Eliminado', 'Eliminado')], default='Borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='idpublicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sitio.publicacion'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
