# Generated by Django 3.1 on 2020-10-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0006_auto_20201015_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='estadoPublicacion',
            field=models.CharField(blank=True, choices=[('Publicado', 'Publicado'), ('Borrador', 'Borrador'), ('Oculta', 'Oculta'), ('Eliminado', 'Eliminado'), ('Denunciado', 'Denunciado')], max_length=50, null=True),
        ),
    ]
