# Generated by Django 3.1 on 2020-09-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0006_merge_20200928_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='materia',
            field=models.CharField(choices=[('Matemáticas', 'Matemáticas'), ('Sociales', 'Ciencias Sociales'), ('Naturales', 'Ciencias Naturales'), ('Lengua', 'Lengua'), ('InglesI', 'InglésI'), ('InglesII', 'InglésII'), ('InglesIII', 'InglésIII'), ('Literatura', 'Literatura'), ('Historia', 'Historia'), ('Química', 'Química'), ('Informática', 'Informática')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='tipoPublicacion',
            field=models.CharField(blank=True, choices=[('Primario', 'Nivel Primario'), ('Secundario', 'Nivel Secundario'), ('Universitarios', 'Nivel Universitarios')], max_length=50, null=True),
        ),
    ]
