# Generated by Django 3.1 on 2020-10-11 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0009_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='idpublicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sitio.publicacion'),
        ),
    ]
