# Generated by Django 3.1 on 2020-10-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0010_auto_20201011_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
