# Generated by Django 3.1 on 2020-10-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0011_auto_20201012_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.CharField(max_length=1000),
        ),
    ]
