# Generated by Django 3.1 on 2020-10-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0014_auto_20201012_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='ubicacionGeografica',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
