# Generated by Django 3.1 on 2020-10-12 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0015_publicacion_ubicaciongeografica'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcontacto',
            name='estadoSolicitud',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudcontacto',
            name='idPublicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sitio.publicacion'),
        ),
    ]
