# Generated by Django 3.1 on 2020-10-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0016_auto_20201012_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='solicitudcontacto',
            name='id',
        ),
        migrations.AddField(
            model_name='comentario',
            name='idComentario',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudcontacto',
            name='idSolicitud',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
