# Generated by Django 3.1 on 2020-10-13 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0017_auto_20201013_0034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolicitudContacto',
        ),
    ]
