# Generated by Django 3.1 on 2020-10-13 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Sitio', '0018_delete_solicitudcontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudContacto',
            fields=[
                ('idSolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('estadoSolicitud', models.CharField(blank=True, choices=[('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('idPublicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sitio.publicacion')),
                ('idUsuarioReceptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_receive', to=settings.AUTH_USER_MODEL)),
                ('idUsuarioSolicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_create', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
