# Generated by Django 3.1 on 2020-10-13 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0019_solicitudcontacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
