# Generated by Django 3.1 on 2020-10-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0021_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcontacto',
            name='idSolicitud',
        ),
        migrations.AddField(
            model_name='solicitudcontacto',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
