# Generated by Django 3.1 on 2020-10-13 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sitio', '0022_auto_20201013_0037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
